### ISSUE TITLE
Version Check

### ISSUE THREAD

**Issue by kasimi** [satanasov/activenotifications#11]
The version check for 3.2.x is broken for some reason, can you fix it please?

**Comment by satanasov** [comment]
Fixed - needed version to be hard coded.

**Comment by kasimi** [comment]
This is still not fixed. Version check in the ACP isn't working.
